apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-php-deployment
  namespace: hello-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-php
  template:
    metadata:
      labels:
        app: hello-php
    spec:
      imagePullSecrets:
        - name: nexus-secret
      containers:
      - name: hello-php
        image: 127.0.0.1:30085/my-repository/hello-php:v003
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-php-service
  namespace: hello-php
spec:
  selector:
    app: hello-php
  ports:
    - protocol: TCP
      port: 8000  # Service port
      targetPort: 8000  # Container port
  type: ClusterIP
